# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  displayName: TF_Install
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  displayName: TF_Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN_Project06'
    backendAzureRmResourceGroupName: 'S2-RG-Project06'
    backendAzureRmStorageAccountName: 'saproject06421433911'
    backendAzureRmContainerName: 'cproject06421433911'
    backendAzureRmKey: 'main.tfstate'
    
- task: TerraformTaskV3@3
  displayName: TF_Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    
- task: TerraformTaskV3@3
  displayName: TF_Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=main.tfplan'
    environmentServiceNameAzureRM: 'SPN_Project06'

- task: TerraformTaskV3@3
  displayName: TF_Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: 'SPN_Project06'

- task: SqlAzureDacpacDeployment@1
  displayName: TF_SQL1
  inputs:
    azureSubscription: 'SPN_Project06'
    AuthenticationType: 'server'
    ServerName: 'sqlproject06421433911.database.windows.net'
    DatabaseName: 'dba'
    SqlUsername: 'admindba'
    SqlPassword: 'ABCabc123.42'
    deployType: 'SqlTask'
    SqlFile: 'dba01.sql'
    IpDetectionMethod: 'AutoDetect'

- task: SqlAzureDacpacDeployment@1
  displayName: TF_SQL2
  inputs:
    azureSubscription: 'SPN_Project06'
    AuthenticationType: 'server'
    ServerName: 'sqlproject06421433911.database.windows.net'
    DatabaseName: 'dba'
    SqlUsername: 'admindba'
    SqlPassword: 'ABCabc123.42'
    deployType: 'SqlTask'
    SqlFile: 'dba02.sql'
    IpDetectionMethod: 'AutoDetect'